### PR TITLE
feat: add openldap plugin

### PR DESCRIPTION
**Pull request by imxw**
# Summary

- add new plugin OpenLDAP which can achieve unified identity authentication
- add related documents
## Key Points

- [x] Documentation (new or existing) is updated.

### Related Issues

#284

### CODE REVIEW

**Review by lfbdev — COMMENTED** [review]
build_linux_amd64.sh  should be updated.

Add  such as "go build -buildmode=plugin -trimpath -gcflags="all=-N -l" -o .devstream/openldap-${GOOS}-${GOARCH}_${VERSION}.so ..." into the file

**Review by daniel-hutao — APPROVED** [review]

**Comment by daniel-hutao** [comment]
LGTM!!!

**Comment by imxw** [comment]
> build_linux_amd64.sh should be updated.
> 
> Add such as "go build -buildmode=plugin -trimpath -gcflags="all=-N -l" -o .devstream/openldap-${GOOS}-${GOARCH}_${VERSION}.so ..." into the file

Yes, I have modified the file.

**Comment by imxw** [comment]
> > build_linux_amd64.sh should be updated.
> > Add such as "go build -buildmode=plugin -trimpath -gcflags="all=-N -l" -o .devstream/openldap-${GOOS}-${GOARCH}_${VERSION}.so ..." into the file
> 
> Yes, I have modified the file.

Got it, I only changed the Makefile

**Review by lfbdev — APPROVED** [review]

**Comment by IronCore864** [comment]
Very good, thanks a lot! @imxw 

We are going to do some manual local tests before merging. Will keep you posted.

**Comment by IronCore864** [comment]
Hello @imxw, great job! This will be our first community plugin and it comes much earlier than we expected. Kudos!

I have 3 suggestions after testing:

1. In the doc, in the example config, maybe add `replicaCount: 1` to the `values_yaml` section, because most people would like to test it locally before deploying it elsewhere, and it's highly likely that their local environment is a one-node mini K8s cluster like `minikube` or `kind`.
2. For the same reason, in the example config, in the `values_yaml` section, change `persistence.enabled` to `false`.
3. The `values_yaml` section contains _a lot of_ default values from this helm chart, for example, `LDAP_LOG_LEVEL`, etc. When installing the chart, the values_yaml will be used on top of the default values from this chart, so it's not necessary to copy the default values from this chart. If the `values_yaml` section is too long, the doc isn't easy to read.

Please rethink what's the best way to put a short and easy-to-ready example in the doc with only necessary values.

**Comment by IronCore864** [comment]
One more small issue on the doc: please pay attention to "[title case](https://en.wikipedia.org/wiki/Title_case)".

E.g., instead of "Description of key fields in values_yaml", "Description of Key Fields in `values_yaml`" is much better. If you are unsure about it, try the [title case converter](https://titlecaseconverter.com/).

@imxw

**Review by IronCore864 — CHANGES_REQUESTED** [review]
No more comments; see the conversation for details.

**Comment by imxw** [comment]
> Hello @imxw, great job! This will be our first community plugin and it comes much earlier than we expected. Kudos!
> 
> I have 3 suggestions after testing:
> 
> 1. In the doc, in the example config, maybe add `replicaCount: 1` to the `values_yaml` section, because most people would like to test it locally before deploying it elsewhere, and it's highly likely that their local environment is a one-node mini K8s cluster like `minikube` or `kind`.
> 2. For the same reason, in the example config, in the `values_yaml` section, change `persistence.enabled` to `false`.
> 3. The `values_yaml` section contains _a lot of_ default values from this helm chart, for example, `LDAP_LOG_LEVEL`, etc. When installing the chart, the values_yaml will be used on top of the default values from this chart, so it's not necessary to copy the default values from this chart. If the `values_yaml` section is too long, the doc isn't easy to read.
> 
> Please rethink what's the best way to put a short and easy-to-ready example in the doc with only necessary values.

Thank you for your suggestion, I will make some changes to the document

**Review by IronCore864 — APPROVED** [review]

**Comment by IronCore864** [comment]
Closes #284

**Pull request merged**
