### PR TITLE
doc: update architecture overview

### PR DESCRIPTION
**Pull request by IronCore864**
# Summary

## Key Points

- [ ] This is a breaking change.
- [x] Documentation (new or existing) is updated.

## Description

Architecture diagram and documentation update.

### Related Issues

https://github.com/merico-dev/stream/issues/31

### CODE REVIEW

**Comment by IronCore864** [comment]
Merge and delete the feature branch after reviewing. @lfbdev @daniel-hutao

**Review by daniel-hutao — COMMENTED** [review]
/lgtm

**Comment by daniel-hutao** [comment]
@lfbdev Please take a review and merge this pr if it is lgty(ou). Don't forget to delete this branch *doc-architecture* after it is merged.

**Pull request merged**
